[2024-11-10T05:44:56.970+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-10T05:44:56.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_news_crawler.fetch_news_data manual__2024-11-10T05:44:45.630350+00:00 [queued]>
[2024-11-10T05:44:57.014+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_news_crawler.fetch_news_data manual__2024-11-10T05:44:45.630350+00:00 [queued]>
[2024-11-10T05:44:57.015+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-10T05:44:57.062+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_news_data> on 2024-11-10 05:44:45.630350+00:00
[2024-11-10T05:44:57.101+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_news_crawler', 'fetch_news_data', 'manual__2024-11-10T05:44:45.630350+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/nh_news_crawling.py', '--cfg-path', '/tmp/tmp6dnsry9t']
[2024-11-10T05:44:57.094+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-10T05:44:57.104+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask fetch_news_data
[2024-11-10T05:44:57.111+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2024-11-10T05:44:57.287+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_news_crawler.fetch_news_data manual__2024-11-10T05:44:45.630350+00:00 [running]> on host 78c1584db90c
[2024-11-10T05:44:57.519+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_news_crawler' AIRFLOW_CTX_TASK_ID='fetch_news_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T05:44:45.630350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T05:44:45.630350+00:00'
[2024-11-10T05:44:57.521+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-10T05:44:57.522+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-10T05:44:57.522+0000] {logging_mixin.py:190} INFO - Current task name:fetch_news_data state:running start_date:2024-11-10 05:44:56.999889+00:00
[2024-11-10T05:44:57.523+0000] {logging_mixin.py:190} INFO - Dag name:daily_news_crawler and current dag run status:running
[2024-11-10T05:44:57.523+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-10T05:45:00.173+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nh_news_crawling.py", line 47, in fetch_news_data
    news_df.to_csv(file_path, mode='w', header=True, index=False)   # 파일이 없으면 새로 생성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/Users/wltn4/OneDrive/바탕 화면/새 폴더/대외활동/NH 투자증권/nh_env/nh-***'
[2024-11-10T05:45:00.215+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-10T05:45:00.216+0000] {logging_mixin.py:190} INFO - Task start:2024-11-10 05:44:56.999889+00:00 end:2024-11-10 05:45:00.215049+00:00 duration:3.21516
[2024-11-10T05:45:00.217+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_news_data> dag:<DAG: daily_news_crawler> dagrun:<DagRun daily_news_crawler @ 2024-11-10 05:44:45.630350+00:00: manual__2024-11-10T05:44:45.630350+00:00, state:running, queued_at: 2024-11-10 05:44:45.747207+00:00. externally triggered: True>
[2024-11-10T05:45:00.217+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: 'C:/Users/wltn4/OneDrive/바탕 화면/새 폴더/대외활동/NH 투자증권/nh_env/nh-***'
[2024-11-10T05:45:00.218+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_news_crawler, task_id=fetch_news_data, run_id=manual__2024-11-10T05:44:45.630350+00:00, execution_date=20241110T054445, start_date=20241110T054456, end_date=20241110T054500
[2024-11-10T05:45:00.248+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-10T05:45:00.249+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task fetch_news_data (Cannot save file into a non-existent directory: 'C:/Users/wltn4/OneDrive/바탕 화면/새 폴더/대외활동/NH 투자증권/nh_env/nh-***'; 207)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/nh_news_crawling.py", line 47, in fetch_news_data
    news_df.to_csv(file_path, mode='w', header=True, index=False)   # 파일이 없으면 새로 생성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/Users/wltn4/OneDrive/바탕 화면/새 폴더/대외활동/NH 투자증권/nh_env/nh-***'
[2024-11-10T05:45:00.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-10T05:45:00.320+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-10T05:45:00.322+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
